name: Deploy to AWS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    
    - name: Setup Node.js for CDK
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install AWS CDK
      run: npm install -g aws-cdk
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    
    - name: Build application
      run: |
        dotnet restore
        dotnet publish app/Bookstore.Web/Bookstore.Web.csproj \
          -p:PublishProfile=FolderProfile \
          -c Release
    
    - name: Deploy infrastructure
      run: |
        cd app/Bookstore.Cdk
        dotnet restore
        cdk deploy BobsBookstoreCore --require-approval never